os: Visual Studio 2019
version: 3.0.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

build_script:
  - ps: .\Build.ps1

after_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "artifacts\coverage.cobertura.xml"

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\MartinCostello.SqlLocalDb.TestApp.*
  - path: artifacts\coverage*.xml

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: NuGet
    api_key:
      secure: jt9LbilCxwYKHpi85v3TWxkFxHVwLRgtPlwceTK2EWI/Z2dawe4+aPb6wAS1LGtZ
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true
